### ISSUE TITLE
Cannot connect over Wi-Fi

### ISSUE THREAD

**Issue by jcasman** [codetricity/oppkey_tester_ricoh_theta#2]
For both an emulated device (sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)) and a physical device (Pixel 4 (mobile) • 9B121FFAZ004TL • android-arm64 • Android 11 (API 30)), the app runs but cannot connect over Wi-Fi. 

Tested Wi-Fi connection independently with RICOH THETA app. Works.

<img width="225" alt="wifi-issue" src="https://user-images.githubusercontent.com/1075520/96798428-c2044480-13b5-11eb-9416-5af56fe1beaa.png">

**Comment by codetricity** [comment]
![image](https://user-images.githubusercontent.com/5799860/97135013-53ecb400-170c-11eb-9aa3-d39b45e857f0.png)

As we're not targeting iOS or Android, only Windows and Linux.  I'm not sure I would classify it as an issue unless it doesn't work on Windows.  

It appears that HTTP requests are disabled on android and ios, but can be enabled.

https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android

![image](https://user-images.githubusercontent.com/5799860/97134395-5bab5900-170a-11eb-8726-b735ae330036.png)
![image](https://user-images.githubusercontent.com/5799860/97134430-6ebe2900-170a-11eb-81b0-5c606bf6f882.png)
